### PR TITLE
PassPartumChrome: Added Machine Translation to the extension

### PR DESCRIPTION
**Pull request by magalaReuben**
It detects the langage used by the browser and sends a request to a server that performs the translation (Currently supports german) model still getting better, currently adding machine laerning monitoring for security monitoring, will be done with server hosting by today, hopefully the translation will be happening from everywhere after server hosting. The server code is at: [https://github.com/magalaReuben/passepartum_server](https://github.com/magalaReuben/passepartum_server) : 04-06-2023

### CODE REVIEW

**Comment by costa-jonathan** [comment]
Hey @magalaReuben,
I am happy for your motivated commits. However i am not quite sure yet if we will use them.
Translation is important but as mostly people from TUM are going to use it I think we will mostly rely on English and German. These two can be implemented without any 3rd party server requests.
I will still have a look in a couple of weeks, are you currently hosting the django app somewhere? if yes where?

The pacman game is a cute addition however I don't quite think it is needed. I will still think about it.

**Comment by ywaine** [comment]
I think the pacman extension should be a priority, it will increase our ability to draw user attention to the app.

**Comment by magalaReuben** [comment]
Okay let me look into it ways in how I can implement this translation
without a third party server

**Comment by magalaReuben** [comment]
okay let me see in which ways i can increase user engagement with it

**Pull request merged**
